Assignment/Models/DataModels/AuditLog.cs
namespace Assignment.Models.DataModels
{
   
        public class AuditLog
        {
            public int Id { get; set; }
            public string Action { get; set; }
            public int Username { get; set; }
            public DateTime Timestamp { get; set; }
            public string Details { get; set; }
        }

    
}

Assignment/Models/DataModels/BulkProductDataModel.cs
namespace Assignment.Models.DataModels
{
    public class BulkProductDataModel
    {
    }
}

Assignment/Models/DataModels/ProductDataModel.cs
using System.ComponentModel.DataAnnotations;

namespace Assignment.Models.DataModels
{
    public class ProductDataModel
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required, RegularExpression(@"^\d{10}$")]
        
        public decimal Price { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime Modifieddate { get; set; }  
        public int CreatedBy {  get; set; } 
        public int ModifiedBy { get; set; } 
        public bool IsDelete { get; set; }
        [Required]
        public string ImagePath { get; set; }
    }
}

Assignment/Models/ErrorViewModel.cs
namespace Assignment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment/Models/ViewModels/AuditViewModel.cs
namespace Assignment.Models.ViewModels
{
    public class AuditViewModel
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public int Username { get; set; }
        public string name { get; set; }
        public DateTime Timestamp { get; set; }
        public string Details { get; set; }
        public AuditViewModel()
        {
            if (Id == 1)
            {
                name = "Operator";

            }
            else
            {
                name = "Admin";

            }
        }
    }
}

Assignment/Models/ViewModels/BulkProductViewModel.cs
namespace Assignment.Models.ViewModels
{
    public class BulkProductViewModel
    {
        public List<ProductViewModel> Products { get; set; }
        
    }
}

Assignment/Models/ViewModels/ProductViewModel.cs
namespace Assignment.Models.ViewModels
{
    public class ProductViewModel
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public IFormFile ImageFile { get; set; }
        public bool? Selected { get; set; }
        public string? ImagePath { get; set; }
    }
}

Assignment/Controllers/AuditController.cs
using Assignment.Models.ViewModels;
using Assignment.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace Assignment.Controllers
{
    public class AuditController : Controller
    {
        private readonly IAudit _auditcontext;
        private readonly IMapper _mapper;

        public AuditController(IAudit audit,IMapper mapper)
        {
            _auditcontext=audit; 
            _mapper=mapper; 
        }
        public async Task<IActionResult> Index()
        {
            var data =_mapper.Map<List<AuditViewModel>>( await _auditcontext.GetAll());
            return View(data.AsEnumerable<AuditViewModel>());
        }
    }
}

Assignment/Controllers/HomeController.cs
using Assignment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Assignment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Assignment/Controllers/ProductsController.cs
using Assignment.Models.ViewModels;
using Assignment.Services;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Drawing;

namespace Assignment.Controllers
{
    public class ProductsController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMapper _mapper;

        public ProductsController(IProductService productService,IMapper mapper)
        {
            _productService= productService;    
            _mapper= mapper;    
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ProductViewModel model)
        { 
            if (ModelState.IsValid)
            {

            }
            await _productService.AddProduct(model,1);
            
            return  RedirectToAction("GetProduct");  

        }
        [HttpGet]
        public async Task<IActionResult> GetProduct(int pagenumber=1,int size=10)
        { var c = await _productService.GetAllProductsCount();
            ViewData["PageCount"] = c<10?1:c/10;
            var data = await _productService.GetAllProducts(pagenumber, size);
            var product = new BulkProductViewModel
            {
                Products = data.Select(s => new ProductViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Price = s.Price,
                    ImagePath = s.ImagePath,


                }).ToList()
            };


            return View(product);

        }
        public async Task<IActionResult> GetProductPagination(int pagenumber = 1, int size = 10)
        {
            var data = await _productService.GetAllProducts(pagenumber, size);
            var product = new BulkProductViewModel
            {
                Products = data.Select(s => new ProductViewModel
                {
                    Id = s.Id,
                    Name = s.Name,
                    Price = s.Price,
                    ImagePath = s.ImagePath,


                }).ToList()
            };


            return PartialView("_ProductPaginationData", product);

        }

        [HttpPost]
        public async Task<IActionResult> Update(List<int> id,int Action)
        {

            if (Action == 1)
            {
                TempData["AllId"]=JsonConvert.SerializeObject(id);
               return Redirect("BulkUpdate");  

            }
            if(Action == 0)
            {

                var data= _mapper.Map<List<ProductViewModel>>(await _productService.GetAllProducts(id));

                await _productService.BulkUpdate(new BulkProductViewModel { Products=data}, 0, 2);
                return Redirect("GetProduct");
            }



            return BadRequest("Error while deleting");



        }
        public async Task<IActionResult> BulkUpdate()
        {
            List<int> id = JsonConvert.DeserializeObject<List<int>>(TempData["AllId"]!.ToString()!)!;
            var data =  _productService.GetAllProducts(id).Result.Select(s => new ProductViewModel
            {
                Price=s.Price,
                ImagePath=s.ImagePath,  
                Name = s.Name,   
               Id=s.Id,

            }).ToList();


            return View(new BulkProductViewModel
            {
                Products=data,
            });
        }
        [HttpPost]
        public async Task<IActionResult> BulkUpdatedata(BulkProductViewModel productViewModels)
        {
             var data=  _productService.BulkUpdate(productViewModels, 1, 1);
 
            return Redirect("GetProduct");
           


        }
        //public async Task<IActionResult> GetAuditData()
        //{
            
        //}
       



    }
}

Assignment/Views/Audit/Index.cshtml
@model IEnumerable<Assignment.Models.ViewModels.AuditViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>


</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Action)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Timestamp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Action)
            </td>
            
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Timestamp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
           
        </tr>
}
    </tbody>
</table>

Assignment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Assignment/Views/Products/BulkUpdate.cshtml
@model Assignment.Models.ViewModels.BulkProductViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<form  asp-action="BulkUpdatedata" asp-controller="Products" method="post" enctype="multipart/form-data">
   <input type="submit" value="Update"  class="btn btn-info"/>
    <table class="table table-danger">
        <thead>
            <tr>
                <th> &nbsp;</th>
                <th>Name</th>   
                <th>Price</th>  
                <th>Image</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in Model.Products)
            {
                @* <tr>
                    <td>
                        <input type="hidden" name="Id[]" value="@product.Id" />
                    </td>
                    <td>  <input type="text" name="Name[]" value="@product.Name" /></td>
                    <td>  <input type="number" name="Price[]" value="@product.Price" /></td>
                    <td>
                        <input type="file" name="ImageFile[]" value="@product.ImagePath" />
                        <img src="@product.ImagePath" alt="@product.Name" width="100" />
                    </td>
                </tr> *@

                <tr>
                    <td>
                        <input type="hidden" name="Products.Index" value="@product.Id" />
                        <input type="hidden" name="Products[@product.Id].Id" value="@product.Id" required />
                    </td>
                    <td>
                        <input type="text" name="Products[@product.Id].Name" value="@product.Name"  required/>
                    </td>
                    <td>
                        <input type="number" name="Products[@product.Id].Price" value="@product.Price" required />
                    </td>
                    <td>
                        <input type="file" name="Products[@product.Id].ImageFile"  value="~/@product.ImagePath"required />
                        <img src="~/@product.ImagePath" alt="@product.Name" width="100" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
</form>

Assignment/Views/Products/GetProduct.cshtml
@model Assignment.Models.ViewModels.BulkProductViewModel

@{
    ViewData["Title"] = "GetProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int count = Convert.ToInt32(ViewData["PageCount"]);
}

<h1>GetProduct</h1>


<div class="addProduct">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" id="openModalBtn">
       Add Product
    </button>

    <div class="float-end ">
    <div class="row flex-lg-row ">
        <div class="btn btn-info col ">
          <form asp-action="Update" asp-controller="Products" method="post" class="p-1 m-2">
                    <div class="hiddenInputsContainer"></div>
            <input type="hidden" name="Action" value="1" id="" />
            <input  type="submit" id="upd" value="Update Product"/>
            </form>
        </div>
            <div class="btn btn-info col ">
                <form asp-action="Update" asp-controller="Products" method="post"  class="p-1 m-2">
                    <div class="hiddenInputsContainer"></div>
                    <input type="hidden" name="Action" value="0" />

                    <input type="submit"id="del" value="Delete Product" />

                </form>
            </div>
     </div>
     </div>
    <!-- Modal -->
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h2>Product Form</h2>
            <form asp-action="Create" asp-controller="Products" method="post" enctype="multipart/form-data" id="productForm">

                <label for="name">Name:</label>
                <input type="text" id="name" name="Name" required>
                <label for="price">Price:</label>
                <input type="number" id="price" name="Price" required>
                <label for="image">Image Path:</label>
                <input type="file" id="image" name="ImageFile" required>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
    <table class="table mytable">
        <thead class="thead-dark">
            <tr>
                <th><input type="checkbox" class="getValuesBtn" id="select-all" /></th>

                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Image</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products.Count > 0)
            {




                @foreach (var product in Model.Products)
                {
                    <tr itemscope="indexer">
                        <td scope="col">
                            <input type="checkbox" class="getValuesBtn" name="SelectedProductIds" value="@product.Id" />
                        </td>
                        <td scope="col">@product.Name</td>
                        <td scope="col">@product.Price</td>
                        <td scope="col">
                            <img src="~/@product.ImagePath" alt="@product.Name" width="100" />
                        </td>
                    </tr>
                }
            }
           
        </tbody>
    </table>




    <ul class="pagination pagination-container">
               
                      
                @for(int i = 1; i <=count; i++)
                {
                  int a = i == 1 ? 0 : i;
                  <li><a href="#@a"  class="page-link">@i</a></li>
                    
                    
                }

            </ul>
<br />
<br />
   

    
    

<script>
    document.getElementById('select-all').addEventListener('click', function (event) {
        var checkboxes = document.querySelectorAll('input[type="checkbox"][name="SelectedProductIds"]');
        checkboxes.forEach(function (checkbox) {
            checkbox.checked = event.target.checked;
        });
    });
</script>

@section Scripts {
    <script src="~/js/model.js">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.19.3/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate.unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"></script>
}

Assignment/Views/Products/_ProductPaginationData.cshtml
@model Assignment.Models.ViewModels.BulkProductViewModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (Model.Products.Count > 0)
{




    @foreach (var product in Model.Products)
    {
        <tr itemscope="indexer">
            <td scope="col">
                <input type="checkbox" class="getValuesBtn" name="SelectedProductIds" value="@product.Id" />
            </td>
            <td scope="col">@product.Name</td>
            <td scope="col">@product.Price</td>
            <td scope="col">
                <img src="~/@product.ImagePath" alt="@product.Name" width="100" />
            </td>
        </tr>
    }
}

Assignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Assignment.styles.css" asp-append-version="true" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div id="loaderContainer">
        <div id="loader"></div>
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Assignment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="GetProduct">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit Log</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Assignment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/model.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>